package org.snailysis.model.utilities.exceptions;

/**
 * This excption shoul be used only during development.
 */
public class NotYetImplementedException extends RuntimeException {
    // AUTO-GENERATED by Eclipse
    private static final long serialVersionUID = 7018133037782382699L;
}
